public interface Repositorio {
    public void adicionaCoima(Coima coima);
    public void adicionaCopia(Copia copia);
    public void adicionaDevolucao(Devolucao devolucao);
    public void adicionaEmprestimo(Emprestimo emprestimo);
    public void adicionaEncomenda(Encomenda encomenda);
    public void adicionaEntradaNovoLivro(EntradaNovoLivro entradaNovoLivro);
    public void adicionaLivro(Livro livro);
    public void adicionaNotificacao(Notificacao notificacao);
    public void adicionaPropostaAquisicao(PropostaAquisicao proposta);
    public void adicionaRequisicao(Requisicao requisicao);
    public void adicionaRequisicaoCompra(RequisicaoCompra requisicaoCompra);
    public void adicionaTipoUtilizador(TipoUtilizador tipo);
    public void adicionaUtilizador(Utilizador utilizador);
    public void adicionaDoacao(Doacao doacao);
    public void adicionaEvento(Eventos evento);
    public void adicionaFatura(Fatura fatura);
    public void adicionaPropostaDoacao(PropostaDoacao propostaDoacao);
    public void adicionaPropostaEvento(PropostaEvento propostaEvento);
    public void adicionaPropostaReservaSala(PropostaReservaSala propostaReservaSala);
    public void adicionaInscricao(Inscricao inscricao);
    public void adicionaIdentidades(Identidade identidade);
    public void adicionaSala(Sala sala);
    public void adicionaVendaLivros(VendaLivros vendaLivros);
    public void adicionaReservaSalas(ReservaSalas reservaSalas);
    public Emprestimo devolveEmprestimoDaRequisicao(Requisicao r);
}
